FROM openjdk:8-jdk-alpine

ADD target/studentRegistrationProject-0.0.1-SNAPSHOT.jar  studentRegistrationProject-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","studentRegistrationProject-0.0.1-SNAPSHOT.jar"]